# Generated by Django 5.2.1 on 2025-05-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitormessage',
            old_name='submitted_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='visitormessage',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
